#!/bin/bash
#
summa=0    #määrame summa algväärtust
read -p  "Sisesta number: " n
#loeme sisestatud korrad
k=0
while [ -n "$n" ]
do
 summa=$(($summa + $n))
 echo "jooksev summa on $summa"
 echo "kui soovid jätkata, sisesta väärtus"
 echo "peatamisesk vajuta lihtsalt enter"
 read -p "sisesta : " n
 k=$(($k + 1)) # suurendame lugemiskord ühe võrra
 clear
done
 echo "arvude summa on $summa"
 echo "kokku sisestaasid arvud $k korda"
