#!/bin/bash
#
#
# arvu paarsuse kontroll
#
# lubame kasutajale sisestada arvu väärtus
echo -n "Sisesta suvaline täisarv: "
read arv
# if lause algus
# kontrollimie, kas arv on positiivne
if [ $arv -ge 0 ]
then
	#arv on positiivne
	echo "$arv on positiivne"
# muidu
else 
	# arv on negatiivne
	echo "$arv on negatiivne"
# if lause lõpp
fi
echo "programmi lõpp"
