#!/bin/bash
#
#kasutaja tervitus
#
# skripti algus
#
# echo "Tere User!"
echo -n "Tere "
echo -n `whoami | cut -c1 | tr [:lower:] [:upper:]` # lõika esimene täht ja muuda suureks
echo -n `whoami | cut -c2-` #d  lõika kõik tähed aöatest 2-st
echo "!"
#
# skripti lõpp
