#!/bin/bash
#
#  kasutajate nimikiri kujul Perenimi, Eesnimi
#
# skripti algus
#
who | cut -f1 -d" " | cut -f2 -d"." > perenimi # lõikame perenimi - see on 2. eelement peale punkti ja salvestame faili
who | cut -f1 -d" " | cut -f1 -d"." > eesnimi # lõikame eesnimi - see on 1. element enne punkti ja salvestame faili paste -d"." perenimi eesnimi > nimed # kleebime eed failid vastavbas järjekorras kokku
cat nimed | sort | uniq # sorteerime väljund ja võtame korduvad välja
#
# skripti lõpp
