#!/bin/bash
#
# kehamassiindeks arvutamine
#
#
echo -n "Sisesta eesnimi ja perenimi: "
read eesnimi perenimi
echo -n "Sisesta kaal (kg): "
read m
echo -n "Sisesta pikkus (m): "
read h
#kontrollimine, kas sisestatud väärtus ei ole tühi
if [ -n "$m" ] && [ -n "$h" ]; then
# arvutame oma kehamassi indeksi
# i = m / h^2
i=$(echo "scale=2;$m/$h^2" | bc)
# kasutaja andmed
echo "Tere $eesnimi $perenimi,"
echo "Teie kehamassiindesk on $i"
# erinevad väljundid
alakaal_t=$(echo "$i < 19" | bc)
normaal_t=$(echo "$i >= 19 && $i < 25" | bc)
ulekaal_t=$(echo "$i >= 25 && $i < 30" | bc)
rasvumine_t=$(echo "$i >= 30" | bc)
# alakaal
if [ $alakaal_t  -eq 1 ]; then
	echo "ALAKAAL"
	echo "ALAKAAl on väga ohtlik"
# noormalkaal
elif [ $normaal_t -eq 1 ]; then
	echo "NORMAALKAAL"
# ülekaaal
elif [ $ulekaal_t -eq 1 ]; then
	echo "ÜLEKAAL"
#rasvumine
elif [ $rasvumine_t -eq 1 ]; then
	echo "rasvumine"
 else
	echo "Probleem skripti kasutamisega"
fi

else
	echo "mass ja pikkus peavad olema arvestatud"
fi
