#!/bin/bash
#
# andmed
#
#
echo -n "Sisesta eesnimi ja perenimi: "
read eesnimi perenimi
echo -n "Sisesta kaal (kg): "
read m
echo -n "Sisesta pikkus (m): "
read h
# arvutame oma kehamassi indeksi
# i = m / h^2
i=$(echo "scale=2;$m/$h^2" | bc)
#väljastamine
echo "$eesnimi $perenimi,"
echo "Teie kehamassiindeks on $i"
